{
  error: MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
      at NativeConnection.Connection.openUri (C:\hotel\shop-backend\node_modules\mongoose\lib\connection.js:825:32)
      at C:\hotel\shop-backend\node_modules\mongoose\lib\index.js:414:10
      at C:\hotel\shop-backend\node_modules\mongoose\lib\helpers\promiseOrCallback.js:41:5
      at new Promise (<anonymous>)
      at promiseOrCallback (C:\hotel\shop-backend\node_modules\mongoose\lib\helpers\promiseOrCallback.js:40:10)
      at Mongoose._promiseOrCallback (C:\hotel\shop-backend\node_modules\mongoose\lib\index.js:1288:10)
      at Mongoose.connect (C:\hotel\shop-backend\node_modules\mongoose\lib\index.js:413:20)
      at C:\hotel\shop-backend\src\utils\connect.ts:11:20
      at Generator.next (<anonymous>)
      at C:\hotel\shop-backend\src\utils\connect.ts:8:71 {
    reason: TopologyDescription {
      type: 'ReplicaSetNoPrimary',
      servers: Map(3) {
        'ac-tqqw5so-shard-00-02.2xr2bqs.mongodb.net:27017' => ServerDescription {
          address: 'ac-tqqw5so-shard-00-02.2xr2bqs.mongodb.net:27017',
          type: 'Unknown',
          hosts: [],
          passives: [],
          arbiters: [],
          tags: {},
          minWireVersion: 0,
          maxWireVersion: 0,
          roundTripTime: -1,
          lastUpdateTime: 783161137,
          lastWriteDate: 0,
          error: MongoNetworkError: connect ETIMEDOUT 3.111.247.83:27017
              at connectionFailureError (C:\hotel\shop-backend\node_modules\mongodb\src\cmap\connect.ts:514:14)
              at TLSSocket.<anonymous> (C:\hotel\shop-backend\node_modules\mongodb\src\cmap\connect.ts:416:16)
              at Object.onceWrapper (node:events:629:26)
              at TLSSocket.emit (node:events:514:28)
              at emitErrorNT (node:internal/streams/destroy:151:8)
              at emitErrorCloseNT (node:internal/streams/destroy:116:3)
              at processTicksAndRejections (node:internal/process/task_queues:82:21) {
            cause: Error: connect ETIMEDOUT 3.111.247.83:27017
                at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
              errno: -4039,
              code: 'ETIMEDOUT',
              syscall: 'connect',
              address: '3.111.247.83',
              port: 27017
            },
            [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
          },
          topologyVersion: null,
          setName: null,
          setVersion: null,
          electionId: null,
          logicalSessionTimeoutMinutes: null,
          primary: null,
          me: null,
          '$clusterTime': null
        },
        'ac-tqqw5so-shard-00-00.2xr2bqs.mongodb.net:27017' => ServerDescription {
          address: 'ac-tqqw5so-shard-00-00.2xr2bqs.mongodb.net:27017',
          type: 'Unknown',
          hosts: [],
          passives: [],
          arbiters: [],
          tags: {},
          minWireVersion: 0,
          maxWireVersion: 0,
          roundTripTime: -1,
          lastUpdateTime: 783161145,
          lastWriteDate: 0,
          error: MongoNetworkError: connect ETIMEDOUT 13.200.188.48:27017
              at connectionFailureError (C:\hotel\shop-backend\node_modules\mongodb\src\cmap\connect.ts:514:14)
              at TLSSocket.<anonymous> (C:\hotel\shop-backend\node_modules\mongodb\src\cmap\connect.ts:416:16)
              at Object.onceWrapper (node:events:629:26)
              at TLSSocket.emit (node:events:514:28)
              at emitErrorNT (node:internal/streams/destroy:151:8)
              at emitErrorCloseNT (node:internal/streams/destroy:116:3)
              at processTicksAndRejections (node:internal/process/task_queues:82:21) {
            cause: Error: connect ETIMEDOUT 13.200.188.48:27017
                at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
              errno: -4039,
              code: 'ETIMEDOUT',
              syscall: 'connect',
              address: '13.200.188.48',
              port: 27017
            },
            [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
          },
          topologyVersion: null,
          setName: null,
          setVersion: null,
          electionId: null,
          logicalSessionTimeoutMinutes: null,
          primary: null,
          me: null,
          '$clusterTime': null
        },
        'ac-tqqw5so-shard-00-01.2xr2bqs.mongodb.net:27017' => ServerDescription {
          address: 'ac-tqqw5so-shard-00-01.2xr2bqs.mongodb.net:27017',
          type: 'Unknown',
          hosts: [],
          passives: [],
          arbiters: [],
          tags: {},
          minWireVersion: 0,
          maxWireVersion: 0,
          roundTripTime: -1,
          lastUpdateTime: 783161350,
          lastWriteDate: 0,
          error: MongoNetworkError: connect ETIMEDOUT 13.201.113.242:27017
              at connectionFailureError (C:\hotel\shop-backend\node_modules\mongodb\src\cmap\connect.ts:514:14)
              at TLSSocket.<anonymous> (C:\hotel\shop-backend\node_modules\mongodb\src\cmap\connect.ts:416:16)
              at Object.onceWrapper (node:events:629:26)
              at TLSSocket.emit (node:events:514:28)
              at emitErrorNT (node:internal/streams/destroy:151:8)
              at emitErrorCloseNT (node:internal/streams/destroy:116:3)
              at processTicksAndRejections (node:internal/process/task_queues:82:21) {
            cause: Error: connect ETIMEDOUT 13.201.113.242:27017
                at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
              errno: -4039,
              code: 'ETIMEDOUT',
              syscall: 'connect',
              address: '13.201.113.242',
              port: 27017
            },
            [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
          },
          topologyVersion: null,
          setName: null,
          setVersion: null,
          electionId: null,
          logicalSessionTimeoutMinutes: null,
          primary: null,
          me: null,
          '$clusterTime': null
        }
      },
      stale: false,
      compatible: true,
      heartbeatFrequencyMS: 10000,
      localThresholdMS: 15,
      setName: 'atlas-iwjpqx-shard-0',
      maxElectionId: null,
      maxSetVersion: null,
      commonWireVersion: 0,
      logicalSessionTimeoutMinutes: null
    },
    code: undefined
  },
  level: 'error',
  message: '[bug] Could not connect to db',
  timestamp: '2024-05-09T06:54:17.317Z'
}
{
  error: MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
      at NativeConnection.Connection.openUri (C:\hotel\shop-backend\node_modules\mongoose\lib\connection.js:825:32)
      at C:\hotel\shop-backend\node_modules\mongoose\lib\index.js:414:10
      at C:\hotel\shop-backend\node_modules\mongoose\lib\helpers\promiseOrCallback.js:41:5
      at new Promise (<anonymous>)
      at promiseOrCallback (C:\hotel\shop-backend\node_modules\mongoose\lib\helpers\promiseOrCallback.js:40:10)
      at Mongoose._promiseOrCallback (C:\hotel\shop-backend\node_modules\mongoose\lib\index.js:1288:10)
      at Mongoose.connect (C:\hotel\shop-backend\node_modules\mongoose\lib\index.js:413:20)
      at C:\hotel\shop-backend\src\utils\connect.ts:11:20
      at Generator.next (<anonymous>)
      at C:\hotel\shop-backend\src\utils\connect.ts:8:71 {
    reason: TopologyDescription {
      type: 'ReplicaSetNoPrimary',
      servers: Map(3) {
        'ac-tqqw5so-shard-00-01.2xr2bqs.mongodb.net:27017' => ServerDescription {
          address: 'ac-tqqw5so-shard-00-01.2xr2bqs.mongodb.net:27017',
          type: 'Unknown',
          hosts: [],
          passives: [],
          arbiters: [],
          tags: {},
          minWireVersion: 0,
          maxWireVersion: 0,
          roundTripTime: -1,
          lastUpdateTime: 789709965,
          lastWriteDate: 0,
          error: MongoNetworkError: connect ETIMEDOUT 13.201.113.242:27017
              at connectionFailureError (C:\hotel\shop-backend\node_modules\mongodb\src\cmap\connect.ts:514:14)
              at TLSSocket.<anonymous> (C:\hotel\shop-backend\node_modules\mongodb\src\cmap\connect.ts:416:16)
              at Object.onceWrapper (node:events:629:26)
              at TLSSocket.emit (node:events:514:28)
              at emitErrorNT (node:internal/streams/destroy:151:8)
              at emitErrorCloseNT (node:internal/streams/destroy:116:3)
              at processTicksAndRejections (node:internal/process/task_queues:82:21) {
            cause: Error: connect ETIMEDOUT 13.201.113.242:27017
                at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
              errno: -4039,
              code: 'ETIMEDOUT',
              syscall: 'connect',
              address: '13.201.113.242',
              port: 27017
            },
            [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
          },
          topologyVersion: null,
          setName: null,
          setVersion: null,
          electionId: null,
          logicalSessionTimeoutMinutes: null,
          primary: null,
          me: null,
          '$clusterTime': null
        },
        'ac-tqqw5so-shard-00-02.2xr2bqs.mongodb.net:27017' => ServerDescription {
          address: 'ac-tqqw5so-shard-00-02.2xr2bqs.mongodb.net:27017',
          type: 'Unknown',
          hosts: [],
          passives: [],
          arbiters: [],
          tags: {},
          minWireVersion: 0,
          maxWireVersion: 0,
          roundTripTime: -1,
          lastUpdateTime: 789709968,
          lastWriteDate: 0,
          error: MongoNetworkError: connect ETIMEDOUT 3.111.247.83:27017
              at connectionFailureError (C:\hotel\shop-backend\node_modules\mongodb\src\cmap\connect.ts:514:14)
              at TLSSocket.<anonymous> (C:\hotel\shop-backend\node_modules\mongodb\src\cmap\connect.ts:416:16)
              at Object.onceWrapper (node:events:629:26)
              at TLSSocket.emit (node:events:514:28)
              at emitErrorNT (node:internal/streams/destroy:151:8)
              at emitErrorCloseNT (node:internal/streams/destroy:116:3)
              at processTicksAndRejections (node:internal/process/task_queues:82:21) {
            cause: Error: connect ETIMEDOUT 3.111.247.83:27017
                at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
              errno: -4039,
              code: 'ETIMEDOUT',
              syscall: 'connect',
              address: '3.111.247.83',
              port: 27017
            },
            [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
          },
          topologyVersion: null,
          setName: null,
          setVersion: null,
          electionId: null,
          logicalSessionTimeoutMinutes: null,
          primary: null,
          me: null,
          '$clusterTime': null
        },
        'ac-tqqw5so-shard-00-00.2xr2bqs.mongodb.net:27017' => ServerDescription {
          address: 'ac-tqqw5so-shard-00-00.2xr2bqs.mongodb.net:27017',
          type: 'Unknown',
          hosts: [],
          passives: [],
          arbiters: [],
          tags: {},
          minWireVersion: 0,
          maxWireVersion: 0,
          roundTripTime: -1,
          lastUpdateTime: 789710187,
          lastWriteDate: 0,
          error: MongoNetworkError: connect ETIMEDOUT 13.200.188.48:27017
              at connectionFailureError (C:\hotel\shop-backend\node_modules\mongodb\src\cmap\connect.ts:514:14)
              at TLSSocket.<anonymous> (C:\hotel\shop-backend\node_modules\mongodb\src\cmap\connect.ts:416:16)
              at Object.onceWrapper (node:events:629:26)
              at TLSSocket.emit (node:events:514:28)
              at emitErrorNT (node:internal/streams/destroy:151:8)
              at emitErrorCloseNT (node:internal/streams/destroy:116:3)
              at processTicksAndRejections (node:internal/process/task_queues:82:21) {
            cause: Error: connect ETIMEDOUT 13.200.188.48:27017
                at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
              errno: -4039,
              code: 'ETIMEDOUT',
              syscall: 'connect',
              address: '13.200.188.48',
              port: 27017
            },
            [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
          },
          topologyVersion: null,
          setName: null,
          setVersion: null,
          electionId: null,
          logicalSessionTimeoutMinutes: null,
          primary: null,
          me: null,
          '$clusterTime': null
        }
      },
      stale: false,
      compatible: true,
      heartbeatFrequencyMS: 10000,
      localThresholdMS: 15,
      setName: 'atlas-iwjpqx-shard-0',
      maxElectionId: null,
      maxSetVersion: null,
      commonWireVersion: 0,
      logicalSessionTimeoutMinutes: null
    },
    code: undefined
  },
  level: 'error',
  message: '[bug] Could not connect to db',
  timestamp: '2024-05-09T08:43:20.870Z'
}
{
  error: MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
      at NativeConnection.Connection.openUri (C:\hotel\shop-backend\node_modules\mongoose\lib\connection.js:825:32)
      at C:\hotel\shop-backend\node_modules\mongoose\lib\index.js:414:10
      at C:\hotel\shop-backend\node_modules\mongoose\lib\helpers\promiseOrCallback.js:41:5
      at new Promise (<anonymous>)
      at promiseOrCallback (C:\hotel\shop-backend\node_modules\mongoose\lib\helpers\promiseOrCallback.js:40:10)
      at Mongoose._promiseOrCallback (C:\hotel\shop-backend\node_modules\mongoose\lib\index.js:1288:10)
      at Mongoose.connect (C:\hotel\shop-backend\node_modules\mongoose\lib\index.js:413:20)
      at C:\hotel\shop-backend\src\utils\connect.ts:11:20
      at Generator.next (<anonymous>)
      at C:\hotel\shop-backend\src\utils\connect.ts:8:71 {
    reason: TopologyDescription {
      type: 'ReplicaSetNoPrimary',
      servers: Map(3) {
        'ac-tqqw5so-shard-00-01.2xr2bqs.mongodb.net:27017' => ServerDescription {
          address: 'ac-tqqw5so-shard-00-01.2xr2bqs.mongodb.net:27017',
          type: 'Unknown',
          hosts: [],
          passives: [],
          arbiters: [],
          tags: {},
          minWireVersion: 0,
          maxWireVersion: 0,
          roundTripTime: -1,
          lastUpdateTime: 789927807,
          lastWriteDate: 0,
          error: MongoNetworkError: connect ETIMEDOUT 13.201.113.242:27017
              at connectionFailureError (C:\hotel\shop-backend\node_modules\mongodb\src\cmap\connect.ts:514:14)
              at TLSSocket.<anonymous> (C:\hotel\shop-backend\node_modules\mongodb\src\cmap\connect.ts:416:16)
              at Object.onceWrapper (node:events:629:26)
              at TLSSocket.emit (node:events:514:28)
              at emitErrorNT (node:internal/streams/destroy:151:8)
              at emitErrorCloseNT (node:internal/streams/destroy:116:3)
              at processTicksAndRejections (node:internal/process/task_queues:82:21) {
            cause: Error: connect ETIMEDOUT 13.201.113.242:27017
                at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
              errno: -4039,
              code: 'ETIMEDOUT',
              syscall: 'connect',
              address: '13.201.113.242',
              port: 27017
            },
            [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
          },
          topologyVersion: null,
          setName: null,
          setVersion: null,
          electionId: null,
          logicalSessionTimeoutMinutes: null,
          primary: null,
          me: null,
          '$clusterTime': null
        },
        'ac-tqqw5so-shard-00-02.2xr2bqs.mongodb.net:27017' => ServerDescription {
          address: 'ac-tqqw5so-shard-00-02.2xr2bqs.mongodb.net:27017',
          type: 'Unknown',
          hosts: [],
          passives: [],
          arbiters: [],
          tags: {},
          minWireVersion: 0,
          maxWireVersion: 0,
          roundTripTime: -1,
          lastUpdateTime: 789927804,
          lastWriteDate: 0,
          error: MongoNetworkError: connect ETIMEDOUT 3.111.247.83:27017
              at connectionFailureError (C:\hotel\shop-backend\node_modules\mongodb\src\cmap\connect.ts:514:14)
              at TLSSocket.<anonymous> (C:\hotel\shop-backend\node_modules\mongodb\src\cmap\connect.ts:416:16)
              at Object.onceWrapper (node:events:629:26)
              at TLSSocket.emit (node:events:514:28)
              at emitErrorNT (node:internal/streams/destroy:151:8)
              at emitErrorCloseNT (node:internal/streams/destroy:116:3)
              at processTicksAndRejections (node:internal/process/task_queues:82:21) {
            cause: Error: connect ETIMEDOUT 3.111.247.83:27017
                at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
              errno: -4039,
              code: 'ETIMEDOUT',
              syscall: 'connect',
              address: '3.111.247.83',
              port: 27017
            },
            [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
          },
          topologyVersion: null,
          setName: null,
          setVersion: null,
          electionId: null,
          logicalSessionTimeoutMinutes: null,
          primary: null,
          me: null,
          '$clusterTime': null
        },
        'ac-tqqw5so-shard-00-00.2xr2bqs.mongodb.net:27017' => ServerDescription {
          address: 'ac-tqqw5so-shard-00-00.2xr2bqs.mongodb.net:27017',
          type: 'Unknown',
          hosts: [],
          passives: [],
          arbiters: [],
          tags: {},
          minWireVersion: 0,
          maxWireVersion: 0,
          roundTripTime: -1,
          lastUpdateTime: 789928035,
          lastWriteDate: 0,
          error: MongoNetworkError: connect ETIMEDOUT 13.200.188.48:27017
              at connectionFailureError (C:\hotel\shop-backend\node_modules\mongodb\src\cmap\connect.ts:514:14)
              at TLSSocket.<anonymous> (C:\hotel\shop-backend\node_modules\mongodb\src\cmap\connect.ts:416:16)
              at Object.onceWrapper (node:events:629:26)
              at TLSSocket.emit (node:events:514:28)
              at emitErrorNT (node:internal/streams/destroy:151:8)
              at emitErrorCloseNT (node:internal/streams/destroy:116:3)
              at processTicksAndRejections (node:internal/process/task_queues:82:21) {
            cause: Error: connect ETIMEDOUT 13.200.188.48:27017
                at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
              errno: -4039,
              code: 'ETIMEDOUT',
              syscall: 'connect',
              address: '13.200.188.48',
              port: 27017
            },
            [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
          },
          topologyVersion: null,
          setName: null,
          setVersion: null,
          electionId: null,
          logicalSessionTimeoutMinutes: null,
          primary: null,
          me: null,
          '$clusterTime': null
        }
      },
      stale: false,
      compatible: true,
      heartbeatFrequencyMS: 10000,
      localThresholdMS: 15,
      setName: 'atlas-iwjpqx-shard-0',
      maxElectionId: null,
      maxSetVersion: null,
      commonWireVersion: 0,
      logicalSessionTimeoutMinutes: null
    },
    code: undefined
  },
  level: 'error',
  message: '[bug] Could not connect to db',
  timestamp: '2024-05-09T08:46:58.711Z'
}
